from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Sum
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from .models import Invoice, Expense
from decimal import Decimal


def index(request):
    return render(request, 'core/index.html')


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'core/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'core/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('index')


@login_required(login_url='/login/')
def dashboard(request):
    invoices = Invoice.objects.filter(user=request.user)
    expenses = Expense.objects.filter(user=request.user)
    total_income = invoices.aggregate(Sum('amount'))['amount__sum'] or Decimal('0')
    total_expenses = expenses.aggregate(Sum('amount'))['amount__sum'] or Decimal('0')
    profit = total_income - total_expenses
    return render(request, 'core/dashboard.html', {
        'invoices': invoices,
        'expenses': expenses,
        'total_income': total_income,
        'total_expenses': total_expenses,
        'profit': profit,
    })


@login_required(login_url='/login/')
def create_invoice(request):
    if request.method == 'POST':
        Invoice.objects.create(
            user=request.user,
            client=request.POST['client'],
            description=request.POST['description'],
            amount=request.POST['amount'],
        )
        return redirect('dashboard')
    return render(request, 'core/invoice.html')


@login_required(login_url='/login/')
def mark_paid(request, pk):
    invoice = get_object_or_404(Invoice, pk=pk, user=request.user)
    invoice.status = 'Paid'
    invoice.save()
    return redirect('dashboard')


@login_required(login_url='/login/')
def download_invoice_pdf(request, pk):
    invoice = get_object_or_404(Invoice, pk=pk, user=request.user)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="invoice_{invoice.id}.pdf"'
    p = canvas.Canvas(response, pagesize=A4)
    width, height = A4

    # Header
    p.setFillColorRGB(0.1, 0.1, 0.18)
    p.rect(0, height - 90, width, 90, fill=1, stroke=0)
    p.setFillColorRGB(1, 1, 1)
    p.setFont("Helvetica-Bold", 28)
    p.drawString(50, height - 55, "SoleTax")
    p.setFont("Helvetica", 12)
    p.drawString(50, height - 75, "Tax Invoice for UK Sole Traders")

    # Invoice info
    p.setFillColorRGB(0, 0, 0)
    p.setFont("Helvetica-Bold", 18)
    p.drawString(50, height - 130, f"INVOICE #{invoice.id:04d}")
    p.setFont("Helvetica", 11)
    p.setFillColorRGB(0.4, 0.4, 0.4)
    p.drawString(50, height - 152, f"Date: {invoice.date}")
    p.drawString(50, height - 170, f"Status: {invoice.status}")

    # Divider
    p.setStrokeColorRGB(0.8, 0.8, 0.8)
    p.line(50, height - 185, width - 50, height - 185)

    # Bill To
    p.setFillColorRGB(0, 0, 0)
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, height - 215, "BILL TO:")
    p.setFont("Helvetica", 12)
    p.drawString(50, height - 235, invoice.client)

    # Description box
    p.setFillColorRGB(0.97, 0.97, 0.97)
    p.rect(50, height - 330, width - 100, 60, fill=1, stroke=0)
    p.setFillColorRGB(0, 0, 0)
    p.setFont("Helvetica-Bold", 11)
    p.drawString(60, height - 285, "DESCRIPTION")
    p.drawString(width - 150, height - 285, "AMOUNT")
    p.setFont("Helvetica", 11)
    p.drawString(60, height - 305, invoice.description[:60])
    p.drawString(width - 150, height - 305, f"£{invoice.amount}")

    # Total
    p.setFillColorRGB(0.1, 0.1, 0.18)
    p.rect(width - 200, height - 390, 150, 45, fill=1, stroke=0)
    p.setFillColorRGB(1, 1, 1)
    p.setFont("Helvetica-Bold", 11)
    p.drawString(width - 190, height - 368, "TOTAL DUE")
    p.setFont("Helvetica-Bold", 14)
    p.drawString(width - 190, height - 385, f"£{invoice.amount}")

    # Footer
    p.setFillColorRGB(0.6, 0.6, 0.6)
    p.setFont("Helvetica", 9)
    p.drawString(50, 40, "Generated by SoleTax | soletax.pythonanywhere.com | Simple Tax Tool for UK Freelancers")
    p.line(50, 55, width - 50, 55)

    p.showPage()
    p.save()
    return response


@login_required(login_url='/login/')
def add_expense(request):
    if request.method == 'POST':
        Expense.objects.create(
            user=request.user,
            description=request.POST['description'],
            amount=request.POST['amount'],
            category=request.POST['category'],
        )
        return redirect('dashboard')
    categories = Expense.CATEGORY_CHOICES
    return render(request, 'core/expense.html', {'categories': categories})


@login_required(login_url='/login/')
def tax_report(request):
    invoices = Invoice.objects.filter(user=request.user)
    expenses = Expense.objects.filter(user=request.user)
    total_income = invoices.aggregate(Sum('amount'))['amount__sum'] or Decimal('0')
    total_expenses = expenses.aggregate(Sum('amount'))['amount__sum'] or Decimal('0')
    profit = total_income - total_expenses
    tax_estimate = profit * Decimal('0.20')
    return render(request, 'core/tax_report.html', {
        'invoices': invoices,
        'expenses': expenses,
        'total_income': total_income,
        'total_expenses': total_expenses,
        'profit': profit,
        'tax_estimate': tax_estimate,
    })
